main:
    model: PPO2
    policy: CustomCnnPolicy
    n_workers: 2
    n_steps: 10000
models:
    PPO2:
        gamma: 0.9
        n_steps: 128
        ent_coef: 0.01
        learning_rate: 0.0004
        vf_coef: 0.5
        max_grad_norm: 0.5
        lam: 0.98
        nminibatches: 4
        noptepochs: 3
        cliprange: 0.2
        full_tensorboard_log: false
        verbose: 1
    A2C: {}
    DDPG: {}
policies:
    CnnPolicy: {}
    CustomCnnPolicy:
        filters:
        - 32
        - 32
        - 128
        kernel_size:
        - 3
        - 6
        - 6
        stride:
        - 2
        - 2
        - 1
        lstm: []
        shared: []
        h_actor:
        - 128
        - 64
        - 32
        h_critic:
        - 64
        - 16
        activ: relu
        pd_init_scale: 1
        conv_init_scale: 1.412
        kernel_initializer: glorot_normal_initializer
        init_bias: 0.5
    CustomCnnLstmPolicy: {}
    MlpPolicy: {}
drawer:
    scale_factor: 5
    base_intensity: 50
    height_scaling: 1
    layer_drawing: false
    layer_count: 2
    layer_threshold: 20
    placement_correction: 8
    load_space_boundary: 0
    queue_item_count: 2
    queue_type: column
    queue_choice_indicator: true
    queue_image_size:
    - 12
    - 12
    queue_scaling: 2
    queue_offset: 2
    draw_borders: true
    border_width: 1
    border_color:
    - 0
    - 0
    - 0
    loadspace_bg_color: 20
    queue_bg_color: 0
    draw_supports: true
    draw_weight: false
    draw_max_w_on_top: true
environment:
    scale: 6.25
    load_space_scaling: 1
    use_image: true
    choose_item: true
    max_height: 0
    verbose: true
    area_fill_reward: 1
    edge_alignment_reward: 1
    base_reward: 0
    orientation_reward: 1
    centered_placement: 1
    end_of_episode: 1
rendering: {}
